port: 8002
timeout: 3000

contents:
  - name: "rs_server"
    addr: "192.168.11.60:5002"
    enable: false
  - name: "demos"
    addr: "192.168.11.30:5003"
    enable: false
  - name: "iguchi"
    addr: "192.168.11.50:5004"
    enable: false

